export enum BuckertizerWarp10Type {
  AND = 'and',
  COUNT = 'count',
  FIRST = 'first',
  JOIN = 'join',
  LAST = 'last',
  MAD = 'mad',
  MAX = 'max',
  MEAN = 'mean',
  MEAN_CIRCULAR = 'mean.circular',
  MEDIAN = 'median',
  MIN = 'min',
  OR = 'or',
  PERCENTILE = 'percentile',
  RMS = 'rms',
  SD = 'sd',
  SD_WELFORD = 'sd.welford',
  SUM = 'sum',
  VAR = 'var',
  VAR_WELFORD = 'var.welford',
}
